import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home() {

const [ data, setData ] = useState([]);
const [ name, setName ] = useState("");
const [ animes, setAnimes ] = useState<any|null>(null);

useEffect(() => {
  axios.get('https://api.jikan.moe/v4/anime')
  .then(item=>setData(item.data.data))
  .catch(er=>console.log("ER> ", er))
},[])

useEffect(() => {
  console.log("DATA > ", data)
  
},[data])

useEffect(() => {
  try{
    const index = data.map(e => e.title).indexOf(name);
    if(index >= 0){
      setAnimes(data[index])
    }
    else{
      setAnimes(null);
    }   
  }
  catch(err){

  }
},[name])

  return (
    <div className={styles.container}>
      <Head>
        <title>Atividade Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <p className={styles.description}>
          Pesquise seu anime aqui:
        </p>
        <input type="text" onChange={(ev)=>setName(ev.target.value)}/>

        <div>
          <ul>
            { animes ?
              <>
                <a href={animes.url}>
                <li key={animes.mal_id}>{animes.title}</li>
                </a>
              </>
              :
              data.map(item => (
              <>
              <a href={item.url}>
              <li key={item.mal_id}>{item.title}</li>
              </a>
              </>
            ))
          }
          </ul>
        </div>
        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
